<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesSeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            [
                'active' => true,
                'address_regex' => '^([13][a-km-zA-HJ-NP-Z1-9]{25,34})|^(bc1([qpzry9x8gf2tvdw0s3jn54khce6mua7l]{39}|[qpzry9x8gf2tvdw0s3jn54khce6mua7l]{59}))$',
                'fee' => '0.0001',
                'max_withdraw_per_transaction' => '2',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.0005',
                'min_withdraw' => '0.0001',
                'name' => 'Bitcoin',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.0001',
                'send_percent' => '0.25',
                'tickers' => ['BTC'],
            ],
            [
                'active' => true,
                'address_regex' => '^(?:0x)?[0-9a-fA-F]{40}$',
                'fee' => '0.001',
                'max_withdraw_per_transaction' => '100',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.005',
                'min_withdraw' => '0.001',
                'name' => 'Ethereum',
                'receive_active' => true,
                'receive_fixed' => '0.001',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.001',
                'send_percent' => '0.25',
                'tickers' => ['ETH'],
            ],
            [
                'active' => true,
                'address_regex' => '^(?:0x)?[0-9a-fA-F]{40}$',
                'fee' => '3.0',
                'max_withdraw_per_transaction' => '100000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '50',
                'min_withdraw' => '10',
                'name' => 'Tether ERC-20',
                'receive_active' => true,
                'receive_fixed' => '3.0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '3.0',
                'send_percent' => '0.25',
                'tickers' => ['USDT','USDTERC','USDTERC20'],
            ],
            [
                'active' => true,
                'address_regex' => '^(?:0x)?[0-9a-fA-F]{40}$',
                'fee' => '3',
                'max_withdraw_per_transaction' => '10000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '50',
                'min_withdraw' => '10',
                'name' => 'USD Coin ERC-20',
                'receive_active' => true,
                'receive_fixed' => '3',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '3',
                'send_percent' => '0.25',
                'tickers' => ['USDC','USDCERC20','USDCERC'],
            ],
            [
                'active' => true,
                'address_regex' => '^r[1-9a-km-zA-HJ-NP-Z]{25,35}$',
                'fee' => '0.3',
                'max_withdraw_per_transaction' => '50000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '10',
                'min_withdraw' => '1',
                'name' => 'Ripple',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => true,
                'send_active' => true,
                'send_fixed' => '0.3',
                'send_percent' => '0.25',
                'tickers' => ['XRP'],
            ],
            [
                'active' => true,
                'address_regex' => '^[T][a-km-zA-HJ-NP-Z1-9]{25,34}$',
                'fee' => '5',
                'max_withdraw_per_transaction' => '100000.000000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '20',
                'min_withdraw' => '10.000000',
                'name' => 'TRON',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '5',
                'send_percent' => '0.25',
                'tickers' => ['TRX'],
            ],
            [
                'active' => true,
                'address_regex' => '^[T][a-km-zA-HJ-NP-Z1-9]{25,34}$',
                'fee' => '1.5',
                'max_withdraw_per_transaction' => '50000.000000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '10.000000',
                'min_withdraw' => '1',
                'name' => 'Tether TRC-20',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '1.5',
                'send_percent' => '0.25000000',
                'tickers' => ['USDTTRC','USDTTRC20'],
            ],
            [
                'active' => true,
                'address_regex' => '[1-9A-HJ-NP-Za-km-z]{32,44}',
                'fee' => '0.03',
                'max_withdraw_per_transaction' => '1000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.1',
                'min_withdraw' => '0.05',
                'name' => 'Solana',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.03',
                'send_percent' => '0.25',
                'tickers' => ['SOL'],
            ],
            [
                'active' => true,
                'address_regex' => '[1-9A-HJ-NP-Za-km-z]{32,44}',
                'fee' => '0.5',
                'max_withdraw_per_transaction' => '100000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '10',
                'min_withdraw' => '1',
                'name' => 'Tether SOL',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.5',
                'send_percent' => '0.25000000',
                'tickers' => ['USDTSOL'],
            ],
            [
                'active' => true,
                'address_regex' => '^[a-zA-Z0-9-_]{48}$',
                'fee' => '0.1',
                'max_withdraw_per_transaction' => '10000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '1',
                'min_withdraw' => '1',
                'name' => 'Toncoin',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => true,
                'send_active' => true,
                'send_fixed' => '0.1',
                'send_percent' => '0.25',
                'tickers' => ['TON'],
            ],
            [
                'active' => true,
                'address_regex' => '^[a-zA-Z0-9-_]{48}$',
                'fee' => '0.5',
                'max_withdraw_per_transaction' => '50000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '1',
                'min_withdraw' => '1',
                'name' => 'Tether TON',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => true,
                'send_active' => true,
                'send_fixed' => '0.5',
                'send_percent' => '0.25000000',
                'tickers' => ['USDTTON','USDTTONCOIN'],
            ],
            [
                'active' => true,
                'address_regex' => '^(?:0x)?[0-9a-fA-F]{40}$',
                'fee' => '0.003',
                'max_withdraw_per_transaction' => '100',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.01',
                'min_withdraw' => '0.001000',
                'name' => 'Binance Coin',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.003',
                'send_percent' => '0.25',
                'tickers' => ['BNB','BNBBEP20','BNB20'],
            ],
            [
                'active' => true,
                'address_regex' => '^(?:0x)?[0-9a-fA-F]{40}$',
                'fee' => '0.0001',
                'max_withdraw_per_transaction' => '100',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.005',
                'min_withdraw' => '0.0001',
                'name' => 'Ethereum BEP-20',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.0001',
                'send_percent' => '0.20000000',
                'tickers' => ['ETHBEP','ETHBEP20'],
            ],
            [
                'active' => true,
                'address_regex' => '^(?:0x)?[0-9a-fA-F]{40}$',
                'fee' => '1',
                'max_withdraw_per_transaction' => '50000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '10',
                'min_withdraw' => '1',
                'name' => 'Tether BEP-20',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '1',
                'send_percent' => '0.25',
                'tickers' => ['USDTBEP','USDTBEP20'],
            ],
            [
                'active' => true,
                'address_regex' => '^(?:0x)?[0-9a-fA-F]{40}$',
                'fee' => '0.5',
                'max_withdraw_per_transaction' => '55000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '5',
                'min_withdraw' => '1',
                'name' => 'USD Coin BEP-20',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.5',
                'send_percent' => '0.2',
                'tickers' => ['USDCBEP','USDCBEP20'],
            ],
            [
                'active' => true,
                'address_regex' => '^((D|A|9)[a-km-zA-HJ-NP-Z1-9]{25,34})$',
                'fee' => '10',
                'max_withdraw_per_transaction' => '10000000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '25',
                'min_withdraw' => '50',
                'name' => 'Dogecoin',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '10',
                'send_percent' => '0.25',
                'tickers' => ['DOGE'],
            ],
            [
                'active' => true,
                'address_regex' => '^((L|M|1|3)[a-km-zA-HJ-NP-Z1-9]{25,34})|^(ltc1([qpzry9x8gf2tvdw0s3jn54khce6mua7l]{39}|[qpzry9x8gf2tvdw0s3jn54khce6mua7l]{59}))$',
                'fee' => '0.01',
                'max_withdraw_per_transaction' => '10000.000000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.025',
                'min_withdraw' => '0.010000',
                'name' => 'Litecoin',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.01',
                'send_percent' => '0.25',
                'tickers' => ['LTC'],
            ],
            [
                'active' => true,
                'address_regex' => '^(4|8)?[0-9A-Z]{1}[0-9a-zA-Z]{93}([0-9a-zA-Z]{11})?$',
                'fee' => '0.01',
                'max_withdraw_per_transaction' => '10000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.1',
                'min_withdraw' => '0.05',
                'name' => 'Monero',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.01',
                'send_percent' => '0.25',
                'tickers' => ['XMR'],
            ],
            [
                'active' => true,
                'address_regex' => '(^(addr|stake)1[ac-hj-np-z02-9]{6,}$)|(^(DdzFFz|Ae2td)[1-9A-HJ-NP-Za-km-z]+)',
                'fee' => '1',
                'max_withdraw_per_transaction' => '500000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '2',
                'min_withdraw' => '2',
                'name' => 'Cardano',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '1',
                'send_percent' => '0.25',
                'tickers' => ['ADA'],
            ],
            [
                'active' => true,
                'address_regex' => '([X7][a-km-zA-HJ-NP-Z1-9]{25,34})$',
                'fee' => '0.03',
                'max_withdraw_per_transaction' => '10000.000000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.05',
                'min_withdraw' => '0.05',
                'name' => 'Dash',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.03',
                'send_percent' => '0.25',
                'tickers' => ['DASH','DSH'],
            ],
            [
                'active' => true,
                'address_regex' => '^([13][a-km-zA-HJ-NP-Z1-9]{25,34})|^((bitcoincash:)?(q|p)[a-z0-9]{41})|^((BITCOINCASH:)?(Q|P)[A-Z0-9]{41})$',
                'fee' => '0.005',
                'max_withdraw_per_transaction' => '10000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.01',
                'min_withdraw' => '0.01',
                'name' => 'Bitcoin Cash',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.005',
                'send_percent' => '0.25',
                'tickers' => ['BCH'],
            ],
            [
                'active' => true,
                'address_regex' => '^(t1|t3)[a-km-zA-HJ-NP-Z1-9]{33}$',
                'fee' => '0.03',
                'max_withdraw_per_transaction' => '10000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.05',
                'min_withdraw' => '0.05',
                'name' => 'Zcash',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.03',
                'send_percent' => '0.25',
                'tickers' => ['ZEC','ZCASH'],
            ],
            [
                'active' => true,
                'address_regex' => '^(?:0x)?[0-9a-fA-F]{40}$',
                'fee' => '0.05',
                'max_withdraw_per_transaction' => '10000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '0.2',
                'min_withdraw' => '0.2',
                'name' => 'Ethereum Classic',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '0.05',
                'send_percent' => '0.25',
                'tickers' => ['ETC'],
            ],
            [
                'active' => true,
                'address_regex' => '^[a-zA-Z0-9-_]{48}$',
                'fee' => '100',
                'max_withdraw_per_transaction' => '1000000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '50',
                'min_withdraw' => '100',
                'name' => 'Notcoin',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => true,
                'send_active' => true,
                'send_fixed' => '100',
                'send_percent' => '0.25',
                'tickers' => ['NOT'],
            ],
            [
                'active' => true,
                'address_regex' => '^(?:0x)?[0-9a-fA-F]{40}$',
                'fee' => '50000.00000000',
                'max_withdraw_per_transaction' => '100000000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '1000000',
                'min_withdraw' => '100000',
                'name' => 'SHIBA INU BEP-20',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => false,
                'send_active' => true,
                'send_fixed' => '50000.00000000',
                'send_percent' => '0.25',
                'tickers' => ['SHIB','SHIBBEP20'],
            ],
            [
                'active' => true,
                'address_regex' => '(^[a-z1-5.]{1,11}[a-z1-5]$)|(^[a-z1-5.]{12}[a-j1-5]$)',
                'fee' => '1',
                'max_withdraw_per_transaction' => '10000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '1',
                'min_withdraw' => '1',
                'name' => 'EOS',
                'receive_active' => false,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => true,
                'send_active' => false,
                'send_fixed' => '1',
                'send_percent' => '0.25',
                'tickers' => ['EOS'],
            ],
            [
                'active' => true,
                'address_regex' => '^G[A-Z2-7]{55}$',
                'fee' => '5',
                'max_withdraw_per_transaction' => '100000',
                'max_withdraw_transactions_per_day' => 1000000,
                'min_receive' => '10',
                'min_withdraw' => '10',
                'name' => 'Stellar',
                'receive_active' => true,
                'receive_fixed' => '0',
                'receive_percent' => '0',
                'require_dest_tag' => true,
                'send_active' => true,
                'send_fixed' => '5',
                'send_percent' => '0.25',
                'tickers' => ['XLM'],
            ],
			// Fiat currencies
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'US Dollar',
				'receive_active' => false,
				'tickers' => ['USD'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Euro',
				'receive_active' => false,
				'tickers' => ['EUR'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'British Pound',
				'receive_active' => false,
				'tickers' => ['GBP'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Japanese Yen',
				'receive_active' => false,
				'tickers' => ['JPY'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Russian Ruble',
				'receive_active' => false,
				'tickers' => ['RUB'],
			],
			// Metals
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Gold',
				'receive_active' => false,
				'tickers' => ['XAU'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Silver',
				'receive_active' => false,
				'tickers' => ['XAG'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Platinum',
				'receive_active' => false,
				'tickers' => ['XPT'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Palladium',
				'receive_active' => false,
				'tickers' => ['XPD'],
			],
			// Stocks
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Apple Inc.',
				'receive_active' => false,
				'tickers' => ['AAPL'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Microsoft Corporation',
				'receive_active' => false,
				'tickers' => ['MSFT'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Tesla, Inc.',
				'receive_active' => false,
				'tickers' => ['TSLA'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Alphabet Inc. (Class C)',
				'receive_active' => false,
				'tickers' => ['GOOG'],
			],
			[
				'active' => true,
				'address_regex' => '',
				'min_receive' => '0',
				'name' => 'Amazon.com, Inc.',
				'receive_active' => false,
				'tickers' => ['AMZN'],
			],
        ];

        foreach ($currencies as $c) {
            $ticker = $c['tickers'][0] ?? strtoupper(substr($c['name'], 0, 4));

            DB::table('currencies')->updateOrInsert(
                ['code' => $ticker],
                [
                    'name' => $c['name'],
                    'symbol' => $ticker,
                    'code' => $ticker,
                    'icon' => $ticker,
                    'network' => $ticker,
                    'exchange_rate' => '1',
                    'status' => $c['active'] ? 'active' : 'inactive',
                    'is_deposit' => (bool) ($c['receive_active'] ?? false),
                    'min_deposit_amount' => (string) ($c['min_receive'] ?? '0'),
                    'address_regex' => (string) ($c['address_regex'] ?? '0'),

                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}


