module.exports = {
    apps: [
        // {
        //     name: 'rates-updater',
        //     script: 'php',
        //     args: 'artisan app:update-rates',
        //     cwd: __dirname,
        //     interpreter: 'none',
        //     instances: 1,
        //     autorestart: true,
        //     watch: false,
        //     max_memory_restart: '1G',
        //     env: {
        //         NODE_ENV: 'production',
        //     },
        //     log_file: './storage/logs/rates-updater.log',
        //     out_file: './storage/logs/rates-updater-out.log',
        //     error_file: './storage/logs/rates-updater-error.log',
        //     time: true,
        // },
        {
            name: 'queue-worker',
            script: 'php',
            args: 'artisan queue:work --sleep=1 --tries=3 --max-time=3600',
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            env: {
                NODE_ENV: 'production',
            },
            log_file: './storage/logs/queue-worker.log',
            out_file: './storage/logs/queue-worker-out.log',
            error_file: './storage/logs/queue-worker-error.log',
            time: true,
        },
        {
            name: 'schedule-worker',
            script: 'php',
            args: 'artisan schedule:work',
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            env: {
                NODE_ENV: 'production',
            },
            log_file: './storage/logs/schedule-worker.log',
            out_file: './storage/logs/schedule-worker-out.log',
            error_file: './storage/logs/schedule-worker-error.log',
            time: true,
        },
        // {
        //     name: 'binance-loop',
        //     script: 'php',
        //     args: 'artisan markets:binance-loop --intervals=1m --sleep=60 --throttle-ms=150 --only-active=1',
        //     cwd: __dirname,
        //     interpreter: 'none',
        //     instances: 1,
        //     autorestart: true,
        //     watch: false,
        //     max_memory_restart: '512M',
        //     env: {
        //         NODE_ENV: 'production',
        //     },
        //     log_file: './storage/logs/binance-loop.log',
        //     out_file: './storage/logs/binance-loop-out.log',
        //     error_file: './storage/logs/binance-loop-error.log',
        //     time: true,
        // },
        {
            name: 'quotes-router',
            script: 'php',
            args: 'artisan quotes:router --ttl=600 --sleep=2',
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '512M',
            env: {
                NODE_ENV: 'production',
            },
            log_file: './storage/logs/quotes-router.log',
            out_file: './storage/logs/quotes-router-out.log',
            error_file: './storage/logs/quotes-router-error.log',
            time: true,
        },
        {
            name: 'quotes-yfinance',
            script: 'php',
            args: 'artisan quotes:yfinance --poll=15 --sync=30',
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
            },
            log_file: './storage/logs/quotes-yfinance.log',
            out_file: './storage/logs/quotes-yfinance-out.log',
            error_file: './storage/logs/quotes-yfinance-error.log',
            time: true,
        },
        {
            name: 'quotes-twelvedata',
            script: 'php',
            args: 'artisan quotes:twelvedata --sync-interval=30',
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '256M',
            env: {
                NODE_ENV: 'production',
            },
            log_file: './storage/logs/quotes-twelvedata.log',
            out_file: './storage/logs/quotes-twelvedata-out.log',
            error_file: './storage/logs/quotes-twelvedata-error.log',
            time: true,
        },
        {
            name: 'yfinance-api',
            script: 'python3',
            args: 'services/yfinance/main.py',
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '512M',
            env: {
                NODE_ENV: 'production',
                YFINANCE_PORT: '8001',
            },
            log_file: './storage/logs/yfinance-api.log',
            out_file: './storage/logs/yfinance-api-out.log',
            error_file: './storage/logs/yfinance-api-error.log',
            time: true,
        },
        {
            name: 'reverb-server',
            script: 'php',
            args: ['artisan', 'reverb:start'],
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '512M',
            env: {
                NODE_ENV: 'production',
            },
            log_file: './storage/logs/reverb.log',
            out_file: './storage/logs/reverb-out.log',
            error_file: './storage/logs/reverb-error.log',
            time: true,
        },
    ],
};
