module.exports = {
    apps: [
        {
            name: 'rates-updater',
            script: 'php',
            args: 'artisan app:update-rates',
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            env: {
                NODE_ENV: 'production',
            },
            log_file: './storage/logs/rates-updater.log',
            out_file: './storage/logs/rates-updater-out.log',
            error_file: './storage/logs/rates-updater-error.log',
            time: true,
        },
        {
            name: 'queue-worker',
            script: 'php',
            args: 'artisan queue:work --sleep=3 --tries=3 --max-time=3600',
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            env: {
                NODE_ENV: 'production',
            },
            log_file: './storage/logs/queue-worker.log',
            out_file: './storage/logs/queue-worker-out.log',
            error_file: './storage/logs/queue-worker-error.log',
            time: true,
        },
        {
            name: 'schedule-worker',
            script: 'php',
            args: 'artisan schedule:work',
            cwd: __dirname,
            interpreter: 'none',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            env: {
                NODE_ENV: 'production',
            },
            log_file: './storage/logs/schedule-worker.log',
            out_file: './storage/logs/schedule-worker-out.log',
            error_file: './storage/logs/schedule-worker-error.log',
            time: true,
        },
    ],
};
